Pull Request - 03 stage
Maks-T/FW-manao pull request #3
Opened 2022-12-04 10:31 UTC by Maks-T

2022-12-05 13:35 UTC, manao-dev requested changes

2022-12-05 13:35 UTC, manao-dev commented on fw/core/component/Base.php
> +    $this->template->render();
рендер тут не нужен, его надо вызывать при необходимости из компонента

2022-12-05 13:35 UTC, manao-dev commented on fw/core/component/Template.php
> +      $this->includeResultModifier();
согласиь эти методы можно оптимизировать, сделать 1 метод includeTemplateFile с передачей названия файла

2022-12-06 16:22 UTC, Maks-T commented on fw/core/component/Base.php
> +    $this->template->render();
исправил

2022-12-06 16:41 UTC, Maks-T commented on fw/core/component/Template.php
> +      $this->includeResultModifier();
Да но есть файлы обязательные, где мне нужно выкинуть ошибку, если файла не существует, и не обязательные, где ошибки не нужны. Поэтому добавил метод includeComponentTemplate для эпилога и модифаера.

2022-12-06 16:43 UTC, merged